version: '3'

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  django:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /start